kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: emp-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "pods"]
  verbs: ["get", "list", "create"] 

